# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
# syntax=docker/dockerfile:1
FROM python:3.12-slim

# set work directory
WORKDIR /app

# install build dependencies and runtime dependencies
# copy project files
COPY pyproject.toml .
COPY uv.lock .
COPY haiguitang_mcp ./haiguitang_mcp
COPY README.md .

# install project
RUN pip install --no-cache-dir .

# default entrypoint
ENTRYPOINT ["haiguitang-mcp"]
